### ISSUE TITLE
Make it save details when you close it

### ISSUE THREAD

**Issue by ghost** [KurozeroPB/CustomRPC#11]
It's very annoying when you close it and you have to enter everything again
please consider

**Comment by Pepijn98** [comment]
It already asks this before closing
![save-settings](https://user-images.githubusercontent.com/14877471/87728812-21a1f100-c7c4-11ea-9c58-38b93031a94c.png)

**Comment by ghost** [comment]
not for me... (on linux)

**Comment by Pepijn98** [comment]
Okay I'll try to test more tomorrow (Friday), it's too late now.
What distro are you using?

**Comment by ghost** [comment]
debian 10

**Comment by ghost** [comment]
also i run it in terminal with the command `custom-rpc`

**Comment by Pepijn98** [comment]
I don't know man, fresh debian 10 installation and it works fine using terminal.
Maybe try reinstalling, see if you're missing or have any broken dependencies?

![debian-10](https://user-images.githubusercontent.com/14877471/87777044-18973b00-c829-11ea-827a-c1cb12cdf5cc.png)

**Comment by ghost** [comment]
crap, i was ctrl-c ing in console
the menu appears if i click the x
thanks for all the effort
