### ISSUE TITLE
updating after stopping breaks it

### ISSUE THREAD

**Issue by eiiiiix** [KurozeroPB/CustomRPC#2]
![screenshot at 2018-09-22 13-00-32](https://user-images.githubusercontent.com/30561378/45919697-9b3a5380-be67-11e8-986b-6d9c28e5d9ff.png)
i get runtime errors if i stop then update on the linux version

also aparently my friend cant use the windows version on windows but im able to use the windows verson on linux

**Comment by Pepijn98** [comment]
Seems like I made a mistake in the last update, will try to fix it as soon as possible. About the windows version, I can't test it right now because I do not own a windows machine nor have a VM ready to go so that might take a little longer.

**Comment by Pepijn98** [comment]
Linux version is update, see https://github.com/KurozeroPB/CustomRPC/releases/tag/v0.1.1
Let me know if it's still happening for you, for me it's fixed.

**Comment by eiiiiix** [comment]
![screenshot at 2018-09-27 13-15-20](https://user-images.githubusercontent.com/30561378/46162893-9c98c100-c257-11e8-9549-19ae25c1a7ec.png)
RIP

**Comment by Pepijn98** [comment]
Which Linux distro etc. are you using?

**Comment by Pepijn98** [comment]
Updated the latest release with the required libraries

**Comment by Pepijn98** [comment]
I'll assume the thumbs-up meant it works now so I'll close the issue.
