### ISSUE TITLE
Building on MacOS needs Qt5 & PyQt5

### ISSUE THREAD

**Issue by ghost** [KurozeroPB/CustomRPC#3]
Please update for building on macOS

**Comment by Pepijn98** [comment]
Hmm since I need to fix some other stuff anyways it seems like a good idea to just upgrade to Qt5, I don't know when this will be finished but I'll be working on it.

**Comment by ghost** [comment]
thanks :)

**Comment by Pepijn98** [comment]
Updated to Qt5, let me know if you still run into problems, I don't know much about macOS but I'll gladly help

**Comment by Pepijn98** [comment]
It's been a week, I'll assume everything went good so I can close the issue.
